"""Freeze the route-stratified retention floor before anything is scored on it.

Stage 1c extends the frozen four-number retention floor to eight by reading the
image-route retention families beside the text-route ones.  This script
hash-binds that decision so the rule cannot be edited between being written down
and being applied.

WHY A FREEZE IS NEEDED FOR A RE-SCORING THAT TRAINS NOTHING
-----------------------------------------------------------
Stage 1c spends no GPU: every prediction it reads was already generated by Stage
1 and Stage 1b.  That makes the usual protection -- "the protocol predates the
training" -- unavailable, because the training has already happened.  What is
still protectable is the order between the RULE and the SCORE.  A basis written
after seeing the stratified numbers could be fitted to them: drop the image
route if it is inconvenient, keep it if it is not, pool instead of stratify, or
narrow the probe.  So the refusal here is keyed on the ANALYSIS REPORT rather
than on adapters, and it is evaluated before any flag is considered.

WHAT IS BOUND
-------------
Four protocol paths (this file, the metric module, the basis builder, the
analyzer), the modules they import whose behaviour is part of the measurement,
the committed reports the basis is derived from, the dataset parquets, and --
separately, because they are gitignored and absent from a clone -- the sha256 of
every prediction parquet the re-scoring will read.  Binding those bytes is what
makes "re-scored from existing predictions" a checkable claim rather than a
description.

The prediction block is verified apart from the rest and reports three outcomes
per path -- match, mismatch, absent -- rather than folding absence into a pass.
A clone without predictions therefore says so explicitly instead of silently
verifying fewer things.

Nothing here reads the sealed confirmation split and nothing edits a frozen
path.  ``retention_selection``, ``hierarchy_metrics``, ``candidate_grid`` and
``seed_replication`` are imported and called; the two prior freezes are read and
re-verified, not rewritten.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

#: Hashing, git state and document flattening come from the Stage-1 freeze so
#: all three Iteration-12 studies verify identically.  Importing also means a
#: change to that frozen file shows up here as a change in behaviour rather
#: than as a silent divergence between copies.
from freeze_iter12_selection_protocol import (
    _flat,
    _git,
    _hash_all,
    _sha256,
)

from granunlearn.config import _find_repo_root
from granunlearn.evaluation import retention_selection as rs
from granunlearn.evaluation import route_stratified_retention as rt
from granunlearn.training.candidate_grid import iter12_grid
from granunlearn.training.seed_replication import (
    ALL_SEEDS,
    PROBE_REPORT,
    STAGE1_FREEZE_REPORT,
    STAGE1_SELECTION_REPORT,
    replicate_id,
    replicates,
    seed_predictions_dir,
    stage1_predictions_dir,
)

OUT_REPORT = "data/reports/mllmu_iter12_route_stratification_freeze.json"
ANALYSIS_REPORT = "data/reports/mllmu_iter12_route_stratified.json"
ROUTE_PROBE_REPORT = "data/reports/mllmu_iter12_route_probe.json"
STAGE1B_FREEZE_REPORT = "data/reports/mllmu_iter12_seed_replication_freeze.json"
STAGE1B_REPORT = "data/reports/mllmu_iter12_seed_replication.json"
STAGE1B_REPAIR = "data/reports/mllmu_iter12_seed_replication.REPAIR.json"

#: The four new files this study is run by.  Hashed so the rule cannot be edited
#: between being frozen and being applied.
PROTOCOL_PATHS = (
    "scripts/freeze_iter12_route_stratification.py",
    "src/granunlearn/evaluation/route_stratified_retention.py",
    "scripts/build_iter12_route_probe.py",
    "scripts/analyze_iter12_route_stratified.py",
)

#: Imported by the four above, so their bytes are part of what this study
#: measures.  ``hierarchy_metrics`` is one of the eighteen paths the
#: confirmation freeze sealed; it appears here as a dependency to be left alone,
#: never as something to edit.
DEPENDS_ON_UNCHANGED = (
    "src/granunlearn/evaluation/retention_selection.py",
    "src/granunlearn/evaluation/hierarchy_metrics.py",
    "src/granunlearn/evaluation/reference_eval.py",
    "src/granunlearn/training/candidate_grid.py",
    "src/granunlearn/training/seed_replication.py",
    "scripts/build_iter12_retention_probe.py",
    "scripts/freeze_iter12_selection_protocol.py",
    "scripts/freeze_iter12_seed_replication.py",
    "scripts/select_unlearning_checkpoints.py",
)

#: Committed evidence the basis is derived from.  Both prior freezes are listed
#: so that this study cannot outlive a change to the protocol it extends.
DATA_PATHS = (
    ROUTE_PROBE_REPORT,
    PROBE_REPORT,
    STAGE1_FREEZE_REPORT,
    STAGE1_SELECTION_REPORT,
    STAGE1B_FREEZE_REPORT,
    STAGE1B_REPORT,
    STAGE1B_REPAIR,
    "data/mllmu_hier_pilot100/queries.parquet",
    "data/mllmu_hier_pilot100/associations.parquet",
)

VOLATILE_FIELDS = ("frozen_at_utc", "git_commit", "git_dirty", "amendments")

#: Verified separately; see the module docstring for why absence is reported
#: rather than passed over.
PREDICTIONS_FIELD = "predictions_bound"
CONTRACT_FIELD = "measurement_contract"

#: Fields whose value depends on gitignored prediction parquets being present.
#: Excluded from the flat document comparison and checked by their own
#: three-valued verifiers instead, so that a clone -- which legitimately has
#: none of those bytes -- reports "fewer things to check" rather than either a
#: false mismatch or a silent pass over a shorter list.
CLONE_DEPENDENT_FIELDS = (PREDICTIONS_FIELD, CONTRACT_FIELD)

#: The splits the re-scoring reads, and the parquet naming convention that goes
#: with them.  Same scope as the frozen basis: the test split stays out.
SPLITS = ("train", "val")

#: Sidecar keys that must be IDENTICAL across every bound parquet.  This is not
#: bookkeeping: the image route is the one whose correctness flips when batch
#: composition changes -- measured at 15 flips out of 4,518 rows between two B0
#: parquets generated from identical adapter bytes at image_batch_size 8 and 1,
#: and every one of the 15 was image-route.  Stage 1c compares image-route
#: numbers ACROSS two prediction directories (the seed-42 replicates are read
#: from Stage 1's), so a contract difference between them would put the headline
#: comparison on two different instruments.  The frozen text-route floor never
#: needed this check because all 484 of its queries are text_to_text; the image
#: stratum does.
CONTRACT_MUST_MATCH = ("batch_size", "image_batch_size", "max_new_tokens",
                       "max_length", "max_image_pixels", "do_sample")
#: Bound beside the generation config, because a contract is not only decoding.
SIDECAR_MUST_MATCH = ("base_model_revision", "contract_version")
DATASET_MUST_MATCH = ("version",)


def sidecar_for(repo_root: Path, parquet_rel: str) -> Path:
    """The provenance sidecar that belongs to one bound parquet."""
    return repo_root / (parquet_rel + ".provenance.json")


def contract_signature(doc: dict[str, Any]) -> dict[str, Any]:
    """The part of a sidecar that decides what instrument produced a parquet."""
    gc = doc.get("generation_config") or {}
    ds = doc.get("dataset") or {}
    return {
        **{k: gc.get(k) for k in CONTRACT_MUST_MATCH},
        **{k: doc.get(k) for k in SIDECAR_MUST_MATCH},
        **{f"dataset.{k}": ds.get(k) for k in DATASET_MUST_MATCH},
    }


def verify_contract(repo_root: Path) -> dict[str, Any]:
    """Are all bound parquets one instrument?  Empty ``problems`` == yes.

    Reported three ways rather than as a boolean: which signatures were seen,
    how many parquets carry each, and which paths are missing a sidecar.  A
    parquet whose sidecar is absent cannot be certified as the same instrument,
    and that is a problem rather than a pass.
    """
    paths = prediction_paths(repo_root)
    sigs: dict[str, dict] = {}
    missing: list[str] = []
    for key, rel in sorted(paths.items()):
        sc = sidecar_for(repo_root, rel)
        if not sc.exists():
            missing.append(f"{key}: {sc.name} is absent")
            continue
        sigs[key] = contract_signature(json.loads(sc.read_text()))
    distinct: dict[str, list[str]] = {}
    for key, sig in sigs.items():
        distinct.setdefault(json.dumps(sig, sort_keys=True), []).append(key)
    #: Kept apart from missing sidecars, because the two have different
    #: consequences.  A conflict between present parquets means the comparison
    #: spans two instruments and is invalid anywhere.  A missing sidecar means
    #: this clone cannot certify that parquet -- which is a fact about the
    #: clone, and is fatal only for a run that needs to read it.
    conflicts = []
    if len(distinct) > 1:
        conflicts.append(
            f"{len(distinct)} distinct measurement contracts across the bound "
            f"parquets: " + " | ".join(
                f"{len(v)} x {k[:120]}" for k, v in sorted(distinct.items())))
    return {
        "num_bound_parquets": len(paths),
        "num_with_a_sidecar": len(sigs),
        "distinct_contracts": len(distinct),
        "contract": json.loads(next(iter(distinct))) if len(distinct) == 1
        else None,
        "keys_compared": sorted({k for sig in sigs.values() for k in sig}),
        "missing_sidecars": missing,
        "contract_conflicts": conflicts,
        "problems": missing + conflicts,
        "one_instrument": not (missing or conflicts),
    }


def prediction_filename(state_id: str) -> str:
    """The train+val parquet name, built the way the Stage-1b analyzer builds it."""
    return f"predictions_{''.join(s[0] for s in SPLITS)}_{state_id}.parquet"


def stage1_states() -> list[str]:
    """MG plus every Stage-1 grid row, derived from the frozen grid.

    Read out of ``iter12_grid`` rather than written down here, so the state list
    cannot drift from the grid the candidates were trained from.
    """
    return ["MG", *(spec.candidate_id for spec in iter12_grid())]


def stage1b_states(repo_root: Path) -> list[tuple[str, str]]:
    """(replicate_id, repo-relative parquet) for all eight replicates.

    The seed-42 replicate was reused from Stage 1, so its predictions live in
    the Stage-1 directory; the six trained replicates live in the Stage-1b one.
    Resolving that here, once, against ``repo_root`` and returning paths
    RELATIVE to it, is what stops the two directories being confused later.
    Joining a resolver's output onto ``repo_root`` a second time is the same
    double-prefix class of bug that killed the Stage-1b control in two seconds.
    """
    stage1 = stage1_predictions_dir(repo_root)
    seeds = seed_predictions_dir(repo_root)
    out: list[tuple[str, str]] = []
    for r in replicates():
        where = stage1 if r.reused else seeds
        name = prediction_filename(r.parent if r.reused else r.replicate_id)
        out.append((r.replicate_id, str((where / name).relative_to(repo_root))))
    return out


def prediction_paths(repo_root: Path) -> dict[str, str]:
    """Every parquet the re-scoring will read, as a repo-relative path.

    Stage 1b's B0 is included even though Stage 1 also has one: the Stage-1b
    control regenerated it, and the re-scoring anchors on the Stage-1 B0, so
    both are bound and the analyzer says which it used.
    """
    stage1 = stage1_predictions_dir(repo_root)
    seeds = seed_predictions_dir(repo_root)
    out: dict[str, str] = {}
    for state in stage1_states():
        out[f"stage1.{state}"] = str(
            (stage1 / prediction_filename(state)).relative_to(repo_root))
    for rid, rel in stage1b_states(repo_root):
        out[f"stage1b.{rid}"] = rel
    out["stage1b.B0"] = str(
        (seeds / prediction_filename("B0")).relative_to(repo_root))
    for key, rel in out.items():
        if rel.startswith("data/data/") or not rel.startswith("data/"):
            raise SystemExit(
                f"{key} resolved to {rel!r}, which is not a repo-relative "
                f"prediction path; the resolvers and this script disagree "
                f"about who supplies the data/ prefix")
    return out


def scored(repo_root: Path) -> bool:
    """Whether the stratified re-scoring has already been filed."""
    return (repo_root / ANALYSIS_REPORT).exists()


def build_freeze(repo_root: Path) -> dict[str, Any]:
    basis_path = repo_root / ROUTE_PROBE_REPORT
    basis = json.loads(basis_path.read_text())
    stage1 = json.loads((repo_root / STAGE1_SELECTION_REPORT).read_text())
    stage1b = json.loads((repo_root / STAGE1B_REPORT).read_text())
    paths = prediction_paths(repo_root)
    present = {k: v for k, v in paths.items() if (repo_root / v).exists()}

    return {
        "iteration": "12",
        "stage": "1c",
        "frozen_at_utc": datetime.now(timezone.utc).isoformat(
            timespec="seconds"),
        "git_commit": _git("rev-parse", "HEAD"),
        "git_dirty": _git("status", "--porcelain") is not None,
        "amendments": [],
        "trains_nothing": True,
        "gpu_hours_required": 0,
        "why_no_gpu_is_required": (
            "Every prediction this study reads was already generated by "
            "Stage 1 (all 4,518 train+val queries for ten states) and "
            "Stage 1b (the same for seven). The image-route retain "
            "families are inside those parquets, so stratifying costs "
            "analysis and no GPU."),
        "what_is_frozen": {
            "floor_numbers": list(rt.FLOOR_NUMBER_KEYS),
            "num_numbers": len(rt.FLOOR_NUMBER_KEYS),
            "routes": [route for route, _ in rt.ROUTES],
            "route_families": {route: list(fams) for route, fams in rt.ROUTES},
            "estimands": list(rs.RETENTION_ESTIMANDS),
            "rule": "candidate >= b0 - epsilon on all eight; a number missing "
                    "on either side disqualifies",
            "epsilon": rs.FLOOR_EPSILON,
            "epsilon_is_a_tolerance_not_a_margin": True,
            "direction": rs.FLOOR_DIRECTION,
            "pooled_reported_but_not_floored": list(rt.POOLED_FAMILIES),
            "scope_splits": list(rt.SCOPE_SPLITS),
            "text_stratum_must_reproduce_the_filed_results": True,
            "consistency_gate": (
                "The analyzer recomputes the frozen four-number floor for every "
                "state and refuses to write unless the stratified verdict "
                "restricted to the text stratum equals it exactly, on every "
                "number and every pass/fail flag. An extension that disagrees "
                "with the rule it extends on the stratum they share is a "
                "different rule wearing its name."),
        },
        "re_decides_nothing": True,
        "what_this_study_does_not_do": (
            "The filed Stage-1 and Stage-1b verdicts stand as filed. This "
            "study reports what an eight-number floor would have said, and "
            "preregisters that floor for Stage 2. It does not reopen a "
            "scored result, and it selects no candidate."),
        "prior_results_it_reports_beside": {
            "stage1_candidates_disqualified": sum(
                1 for c in stage1["candidates"].values()
                if not c["floor"]["eligible"]),
            "stage1_candidates_total": len(stage1["candidates"]),
            "stage1b_parents_passing_on_the_mean": sum(
                1 for v in stage1b["verdicts"].values()
                if v["passes_on_the_mean"]),
        },
        "basis": {
            "report": ROUTE_PROBE_REPORT,
            "sha256": _sha256(basis_path),
            "re_derives_without_reading_a_prediction":
                basis["no_prediction_is_read"]["holds"],
            "probe_entities": basis["reuses_partition"]["probe_entities"],
            "partition_re_derived_and_matched":
                basis["reuses_partition"]["re_derived_and_matched"],
            "smallest_resolvable_gap": basis["numerical_tolerance"][
                "smallest_resolvable_gap_over_the_eight_numbers"],
            "absolute_ceiling_retain_other": basis["power_ceiling"][
                "all splits, both routes (the absolute ceiling)"
            ]["retain_other_total"],
        },
        "extends": {
            "stage1_freeze": STAGE1_FREEZE_REPORT,
            "stage1b_freeze": STAGE1B_FREEZE_REPORT,
            "stage1b_report": STAGE1B_REPORT,
            "stage1b_repair_record": STAGE1B_REPAIR,
            "note": (
                "The Stage-1b result was filed with a repair record beside it, "
                "because the frozen analyzer crashed on a field that decides "
                "nothing. That deviation is part of the evidence this study "
                "extends and is bound here rather than quietly inherited."),
        },
        "states_scored": {
            "stage1": stage1_states(),
            "stage1b": [rid for rid, _ in stage1b_states(repo_root)] + ["B0"],
            "replicate_seeds": list(ALL_SEEDS),
            "replicate_naming": replicate_id("PARENT", 42),
        },
        "hashes": {
            "protocol_paths": _hash_all(repo_root, PROTOCOL_PATHS),
            "depends_on_unchanged": _hash_all(repo_root, DEPENDS_ON_UNCHANGED),
            "data_paths": _hash_all(repo_root, DATA_PATHS),
        },
        PREDICTIONS_FIELD: {
            "count_expected": len(paths),
            "count_present_at_freeze_time": len(present),
            "absent_at_freeze_time": sorted(
                k for k in paths if k not in present),
            "sha256": {k: _sha256(repo_root / v) for k, v in present.items()},
            "paths": paths,
            "note": (
                "Gitignored and therefore absent from a clone. Verified apart "
                "from the rest of the freeze, reporting match, mismatch or "
                "absent per path, so a clone says it has fewer bytes to check "
                "instead of passing on a shorter list."),
        },
        "measurement_contract": verify_contract(repo_root),
        "disclosure": {
            "identified_after_stage1b_was_scored": True,
            "not_blind": True,
            "derived_from_dataset_structure_only": True,
            "evidence": (
                "The image families cover an identical association set to the "
                "text ones (387/387), share zero templates with them, and are "
                "emitted by the sealed hierarchy_metrics as "
                "retain_*_entity_image blocks that the frozen floor never "
                "read. All three facts are properties of queries.parquet and "
                "of the sealed metric, and both are checkable in the basis "
                "report without loading a prediction."),
            "direction_is_against_interest": (
                "Stratifying adds four conditions to the floor and makes it "
                "harder to pass. Measured on the eight Stage-1 candidates, the "
                "image route loses more retention than the text route for 7 of "
                "8, so the extension enlarges the failure it reports rather "
                "than shrinking it."),
            "what_would_have_been_unacceptable": (
                "Choosing between stratifying, pooling and dropping the image "
                "route after seeing which of the three produced the preferred "
                "verdict. All three were computed; the stratified one is "
                "frozen because pooling would average two instruments that do "
                "not measure the same thing, and the pooled numbers are "
                "reported beside the decision so that choice is visible."),
        },
    }


def verify_freeze(repo_root: Path, path: Path | None = None) -> list[str]:
    """Recompute the freeze against the repository. Empty list == matches.

    The prediction block is excluded here and verified by
    :func:`verify_predictions`, because those files are gitignored and their
    absence in a clone is not a mismatch.
    """
    path = path or repo_root / OUT_REPORT
    if not path.exists():
        return [f"{path} does not exist -- the basis is not frozen"]
    old = _flat(json.loads(path.read_text()))
    fresh = _flat(build_freeze(repo_root))
    skip = VOLATILE_FIELDS + CLONE_DEPENDENT_FIELDS
    reasons = []
    for key in sorted(set(old) | set(fresh)):
        if any(key.startswith(f"{v}.") or key == v for v in skip):
            continue
        if old.get(key) != fresh.get(key):
            reasons.append(f"{key}: frozen={old.get(key)!r} "
                           f"now={fresh.get(key)!r}")
    return reasons


def verify_predictions(repo_root: Path,
                       path: Path | None = None) -> dict[str, list[str]]:
    """Three-valued check of the prediction bytes the re-scoring reads."""
    path = path or repo_root / OUT_REPORT
    doc = json.loads(path.read_text())
    block = doc[PREDICTIONS_FIELD]
    frozen: dict[str, str] = block["sha256"]
    paths: dict[str, str] = block["paths"]
    out = {"match": [], "mismatch": [], "absent": []}
    for key, rel in sorted(paths.items()):
        p = repo_root / rel
        if key not in frozen:
            out["absent"].append(f"{key}: not present when the basis was frozen")
        elif not p.exists():
            out["absent"].append(f"{key}: {rel} is absent from this clone")
        elif _sha256(p) != frozen[key]:
            out["mismatch"].append(
                f"{key}: frozen={frozen[key][:16]} now={_sha256(p)[:16]}")
        else:
            out["match"].append(key)
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check-only", action="store_true",
                    help="Verify the committed freeze instead of writing it")
    ap.add_argument("--refreeze", action="store_true",
                    help="Amend an existing freeze, recording the amendment. "
                         "Refused once the re-scoring has been filed.")
    ap.add_argument("--reason", default=None,
                    help="Why the freeze is being amended (with --refreeze)")
    ap.add_argument("--repo-root", default=None)
    args = ap.parse_args()
    repo_root = Path(args.repo_root) if args.repo_root \
        else (_find_repo_root(Path.cwd()) or Path.cwd())
    out = repo_root / OUT_REPORT

    if args.check_only:
        reasons = verify_freeze(repo_root)
        preds = verify_predictions(repo_root) if out.exists() else {
            "match": [], "mismatch": [], "absent": []}
        contract = verify_contract(repo_root) if out.exists() else {
            "contract_conflicts": [], "missing_sidecars": [],
            "distinct_contracts": 0, "num_with_a_sidecar": 0}
        #: A contract conflict is fatal anywhere; missing sidecars are only
        #: fatal for a run that has to read those parquets, and --check-only
        #: does not.
        if reasons or preds["mismatch"] or contract["contract_conflicts"]:
            if reasons:
                print("MISMATCHES:")
                for r in reasons:
                    print(f"  {r}")
            for m in preds["mismatch"]:
                print(f"  PREDICTION {m}")
            for c in contract["contract_conflicts"]:
                print(f"  CONTRACT {c}")
            raise SystemExit(1)
        print(f"OK — the Stage-1c route-stratification freeze still matches "
              f"the repository (volatile fields excluded: "
              f"{list(VOLATILE_FIELDS)}; clone-dependent fields verified "
              f"separately: {list(CLONE_DEPENDENT_FIELDS)})")
        print(f"  predictions bound: {len(preds['match'])} match, "
              f"{len(preds['absent'])} absent from this clone")
        for a in preds["absent"]:
            print(f"    absent: {a}")
        print(f"  measurement contracts: {contract['distinct_contracts']} "
              f"distinct over {contract['num_with_a_sidecar']} sidecar(s); "
              f"{len(contract['missing_sidecars'])} parquet(s) without one")
        return

    #: Evaluated FIRST and unconditionally: no flag, including --refreeze,
    #: reaches past it.  This study trains nothing, so the thing that must not
    #: postdate the rule is the SCORE.
    if scored(repo_root):
        raise SystemExit(
            f"REFUSING to freeze: {ANALYSIS_REPORT} already exists. A basis "
            f"written now would postdate the scores it is supposed to govern, "
            f"and could be fitted to them -- which route to read, whether to "
            f"pool or stratify, and how wide the probe is, are all choices "
            f"whose answer changes once the numbers are visible.")

    document = build_freeze(repo_root)
    if out.exists():
        previous = json.loads(out.read_text())
        if not args.refreeze:
            raise SystemExit(
                f"REFUSING to overwrite {out} (sha256 {_sha256(out)}). It is "
                f"the record that this basis predates its own scoring; "
                f"deleting or replacing it is the one act that would make that "
                f"claim unfalsifiable. --refreeze --reason amends it with the "
                f"change recorded.")
        if not args.reason:
            raise SystemExit("--refreeze requires --reason: an amendment whose "
                             "reason is not written down is indistinguishable "
                             "from a quiet rewrite.")
        old_flat, new_flat = _flat(previous), _flat(document)
        skip = VOLATILE_FIELDS + CLONE_DEPENDENT_FIELDS
        changed = sorted(
            k for k in set(old_flat) | set(new_flat)
            if not any(k.startswith(f"{v}.") or k == v for v in skip)
            and old_flat.get(k) != new_flat.get(k))
        document["amendments"] = [*previous.get("amendments", []), {
            "utc": document["frozen_at_utc"],
            "reason": args.reason,
            "supersedes_sha256": _sha256(out),
            "fields_that_changed": changed,
            "no_score_had_been_filed": True,
        }]
        #: An amendment may rebind the predictions but must keep the ones the
        #: previous freeze recorded, so a byte that was scored cannot be
        #: swapped silently.
        document[PREDICTIONS_FIELD]["sha256"] = {
            **document[PREDICTIONS_FIELD]["sha256"],
            **{k: v for k, v in previous[PREDICTIONS_FIELD]["sha256"].items()},
        }
        out.write_text(json.dumps(document, indent=2) + "\n")
        print(f"Route-stratification freeze AMENDED -> {out}")
        print(f"  reason: {args.reason}")
        print(f"  fields that changed: {changed or '(none)'}")
        return

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(document, indent=2) + "\n")
    print(f"Route-stratified retention floor frozen -> {out}")
    print(f"  {len(rt.FLOOR_NUMBER_KEYS)} numbers over "
          f"{[r for r, _ in rt.ROUTES]}, epsilon {rs.FLOOR_EPSILON}, no margin")
    print(f"  states to score: {len(stage1_states())} Stage-1 + "
          f"{len(stage1b_states(repo_root)) + 1} Stage-1b")
    print(f"  predictions bound: "
          f"{document[PREDICTIONS_FIELD]['count_present_at_freeze_time']} of "
          f"{document[PREDICTIONS_FIELD]['count_expected']}")
    print("  trains nothing; requires 0 GPU-hours")


if __name__ == "__main__":
    main()
